name: subiman
version: 0.1.0
description: Manage Subiquity for Ubuntu Desktop Installer
publish_to: 'none'

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  args: ^2.3.0
  collection: ^1.15.0
  http: ^0.13.4
  meta: ^1.7.0
  package_config: ^2.0.2
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  subiman:
